version: '3.8'

services:
  ldap:
    image: osixia/openldap
    container_name: ${CONTAINER_NAME}
    environment:
      LDAP_ORGANISATION: ${ORG}
      LDAP_DOMAIN: ${DOMAIN}
      LDAP_ADMIN_USERNAME: ${ADMIN_USER}
      LDAP_ADMIN_PASSWORD: ${ADMIN_PASS}
      LDAP_CONFIG_PASSWORD: ${CONFIG_PASS}
      LDAP_READONLY_USER: ${READONLY_USER}
      LDAP_READONLY_USER_USERNAME: ${READONLY_USER_NAME}
      LDAP_READONLY_USER_PASSWORD: ${READONLY_USER_PASS}
    ports:
      - "${PORT}:389"
      - "${HTTPS_PORT}:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin
    container_name: ${ADMIN_CONTAINER_NAME}
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ${LDAP_HOST}
      PHPLDAPADMIN_HTTPS: ${HTTPS}
    ports:
      - "${ADMIN_PORT}:80"
    depends_on:
      - ldap

volumes:
  ldap_data:
  ldap_config:
